spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true